In [1]:
import pandas as pd
df = pd.DataFrame({
    'name':['ram','sam','tom'],
    'Age':[20,29,19]
})
df

  name  Age
0  ram   20
1  sam   29
2  tom   19

In [10]:
df = pd.read_csv(r"c:\Users\USER\OneDrive\Desktop\resltfile.csv")
# df = pd.read_excel(r"c:\Users\USER\Downloads\D10_RANGAMUNI_EXCEL_DEMO_PROJECT.xlsx")
df

,ï»¿video_id,channel_name,title,category,views,likes,dislikes,comments,publish_date,city,status
0,9001,TechWorld,Roadmap to Learn SQL,Education,50000,2500.0,100.0,300.0,01-01-2024,Hyderabad,Active
1,9002,CookWithMe,Tasty Biryani Recipe,Food,30000,1800.0,50.0,200.0,02-01-2024,hyd,active
2,9003,GamingZone,Top 10 Games,Gaming,abc,2000.0,100.0,150.0,03-Jan-24,Mumbai,Active
3,9004,NaN,NaN,Music,20000,NaN,80.0,120.0,04-01-2024,BLR,Inactive
4,9005,FitLife,Workout Tips,Fitness,40000,2200.0,70.0,250.0,05-01-2024,Hyderabad,Active
...,...,...,...,...,...,...,...,...,...,...,...
58,9066,CookWithMe,Quick Meals,Food,30000,1800.0,70.0,200.0,02-03-2024,Hyderabad,Active
59,9067,GamingZone,Apex Legends,Gaming,54000,2700.0,120.0,310.0,03-03-2024,Hyderabad,Active
60,9068,FitLife,Home Workout,Fitness,26000,1400.0,60.0,160.0,04-03-2024,Hyderabad,Active
61,9069,TravelNow,Hill Station,Travel,35000,1900.0,70.0,220.0,05-03-2024,Hyderabad,Active
62,9070,MusicHub,Indie Songs,Music,62000,3100.0,160.0,380.0,06-03-2024,Hyderabad,Active

In [18]:
# df.columns
df.__rpow__

# df.describe()

<bound method OpsMixin.__rpow__ of     ï»¿video_id channel_name                 title   category  views   likes  \
0          9001    TechWorld  Roadmap to Learn SQL  Education  50000  2500.0
1          9002   CookWithMe  Tasty Biryani Recipe       Food  30000  1800.0
2          9003   GamingZone          Top 10 Games     Gaming    abc  2000.0
3          9004          NaN                   NaN      Music  20000     NaN
4          9005      FitLife          Workout Tips    Fitness  40000  2200.0
..          ...          ...                   ...        ...    ...     ...
58         9066   CookWithMe           Quick Meals       Food  30000  1800.0
59         9067   GamingZone          Apex Legends     Gaming  54000  2700.0
60         9068      FitLife          Home Workout    Fitness  26000  1400.0
61         9069    TravelNow          Hill Station     Travel  35000  1900.0
62         9070     MusicHub           Indie Songs      Music  62000  3100.0

    dislikes  comments publish_date       city    status
0      100.0     300.0   01-01-2024  Hyderabad    Active
1       50.0     200.0   02-01-2024        hyd    active
2      100.0     150.0    03-Jan-24     Mumbai    Active
3       80.0     120.0   04-01-2024        BLR  Inactive
4       70.0     250.0   05-01-2024  Hyderabad    Active
..       ...       ...          ...        ...       ...
58      70.0     200.0   02-03-2024  Hyderabad    Active
59     120.0     310.0   03-03-2024  Hyderabad    Active
60      60.0     160.0   04-03-2024  Hyderabad    Active
61      70.0     220.0   05-03-2024  Hyderabad    Active
62     160.0     380.0   06-03-2024  Hyderabad    Active

[63 rows x 11 columns]>

In [20]:
df = pd.read_csv(r"c:\Users\USER\OneDrive\Desktop\resltfile.csv")
# df = pd.read_excel(r"c:\Users\USER\Downloads\D10_RANGAMUNI_EXCEL_DEMO_PROJECT.xlsx")
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ï»¿video_id   63 non-null     int64
 1   channel_name  59 non-null     str
 2   title         57 non-null     str
 3   category      60 non-null     str
 4   views         57 non-null     str
 5   likes         57 non-null     float64
 6   dislikes      58 non-null     float64
 7   comments      58 non-null     float64
 8   publish_date  57 non-null     str
 9   city          62 non-null     str
 10  status        62 non-null     str
dtypes: float64(3), int64(1), str(7)
memory usage: 5.5 KB

       ï»¿video_id       likes    dislikes    comments
count    63.000000    57.00000   58.000000   58.000000
mean   9034.777778  2008.77193   86.551724  229.137931
std      20.063966   697.51618   38.505034   90.984566
min    9001.000000     0.00000    0.000000    0.000000
25%    9017.500000  1500.00000   60.000000  160.000000
50%    9035.000000  1900.00000   80.000000  210.000000
75%    9050.500000  2500.00000  100.000000  300.000000
max    9070.000000  3500.00000  200.000000  500.000000

In [1]:
df.shape

NameError: name 'df' is not defined